version: "3.9"
services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    command: sleep infinity

  superset-init:
    image: apache/superset:latest
    volumes:
      - ../superset_home:/app/superset_home
    command: >
      /bin/sh -c "
      set -e
      python -m superset db upgrade &&
      python -m superset fab create-admin
        --username admin
        --firstname Superset
        --lastname Admin
        --email admin@example.com
        --password admin &&
      python -m superset init
      "

  superset:
    image: apache/superset:latest
    depends_on:
      superset-init:
        condition: service_completed_successfully
    environment:
      SUPERSET_SECRET_KEY: "change_me_to_a_random_hex"
      SUPERSET_CONFIG_PATH: /app/superset_home/superset_config.py
    # use image's default CMD or start gunicorn explicitly:
    # command: /bin/sh -c "exec gunicorn -w 2 -k gevent -b 0.0.0.0:8088 'superset.app:create_app()'"
    ports:
      - "8088:8088"
    volumes:
      - ../superset_home:/app/superset_home
    healthcheck:
      test: ["CMD", "python", "-c",
             "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8088/health').read()"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
