version: "3.9"
services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    command: sleep infinity

  superset-init:
    image: apache/superset:latest
    volumes:
      - ../superset_home:/app/superset_home
    entrypoint: >
      /bin/bash -lc "
      set -e
      superset db upgrade &&
      superset fab create-admin
        --username admin
        --firstname Superset
        --lastname Admin
        --email admin@example.com
        --password admin &&
      superset init
      "

  superset:
    image: apache/superset:latest
    depends_on:
      superset-init:
        condition: service_completed_successfully
    environment:
      SUPERSET_SECRET_KEY: "change_me_to_a_random_hex"
      SUPERSET_CONFIG_PATH: /app/superset_home/superset_config.py
    ports:
      - "8088:8088"
    volumes:
      - ../superset_home:/app/superset_home
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
