services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    command: sleep infinity

  superset-init:
    image: apache/superset:latest
    volumes:
      - ../superset_home:/app/superset_home
    entrypoint: >
      /bin/bash -lc "
      superset db upgrade &&
      superset fab create-admin
        --username admin
        --firstname Superset
        --lastname Admin
        --email admin@example.com
        --password admin &&
      superset init
      "

  superset:
    image: apache/superset:latest
    depends_on:
      - superset-init
    environment:
      SUPERSET_SECRET_KEY: "change_me_to_a_random_hex"
    ports:
      - "8088:8088"
    volumes:
      - ../superset_home:/app/superset_home
